version: '3.9'

services:
  db:
    container_name: "PostgresDB"
    image: "postgres:14.0-alpine"
    restart: always
    environment:
      POSTGRES_USER: wathnak
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wathnak_db
    ports:
      - "5432:5432"
    volumes:
      - "./storage/migrations:/docker-entrypoint-initdb.d/"
  app:
    container_name: "Wathnak"
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - "db:database"
    depends_on:
      - db
    ports:
      - 9000:9000
    command: /home/gradle/buildWorkspace/app/build/distributions/app/bin/app